"""astra_birth.py — Compute and store birth chart at GENESIS.

Run once during first-time setup (GENESIS step).
Generates ASTRA_BIRTH.md, seeds Dasha timeline.

Usage:
    python Runtime/engine/astra_birth.py --base-dir . --date 1996-12-15 --time 14:30
"""

import argparse
import sys
from pathlib import Path

# Ensure workspace root is on sys.path for direct script execution
_this_dir = Path(__file__).resolve().parent
_workspace_root = _this_dir.parent.parent
if str(_workspace_root) not in sys.path:
    sys.path.insert(0, str(_workspace_root))

from Runtime.engine.astra_core import AstraEngine


def generate_birth_md(engine, year, month, day, hour, minute, place="Lome") -> str:
    """Generate ASTRA_BIRTH.md from birth data."""
    chart = engine.compute_birth_chart(year, month, day, hour, minute, place)
    dasha = engine.compute_vimshottari(chart["jd"])
    sade = engine.compute_sade_sati(chart)

    md = f"""# ASTRA Birth Profile

> Generated by astra_birth.py

## Birth Data
- **Birth date:** {year:04d}-{month:02d}-{day:02d}
- **Birth time:** {hour:02d}:{minute:02d} (UTC+0)
- **Location:** {place} ({engine.lat}N, {engine.lon}E)

## Ayanamsa
- **System:** Lahiri (Chitrapaksha)
- **Houses:** Whole Sign (Parashari)

## Lagna (Ascendant)
- **Sign:** {chart['lagna']['rashi']} ({chart['lagna']['deg']}deg)
- **Nakshatra:** {chart['lagna']['nakshatra']} — Pada {chart['lagna']['nakshatra_pada']}
- **Nakshatra Lord:** {chart['lagna']['nakshatra_lord']}

## Graha Positions
| Graha | Rashi | Deg | Nakshatra | Pada | Lord | House | Retro |
|-------|-------|-----|-----------|------|------|-------|-------|
"""
    for name in ["Surya", "Chandra", "Mangala", "Budha", "Guru", "Shukra", "Shani", "Rahu", "Ketu"]:
        g = chart["grahas"].get(name)
        if not g:
            continue
        retro = "R" if g["retrograde"] else ""
        md += f"| {name} | {g['rashi']} | {g['rashi_deg']} | {g['nakshatra']} | {g['nakshatra_pada']} | {g['nakshatra_lord']} | {g.get('house', '?')} | {retro} |\n"

    md += f"""
## House Lords
| House | Lord |
|-------|------|
"""
    for h, lord in list(chart["house_lords"].items())[:12]:
        md += f"| {h} | {lord} |\n"

    if dasha["current_md"]:
        md += f"""
## Current Dasha
- **Mahadasha:** {dasha['current_md']['lord']}
- **Start:** {dasha['current_md']['start']}
- **End:** {dasha['current_md']['end']}
- **Years:** {dasha['current_md']['years']}"""
        if dasha["current_ad"]:
            md += f"""
- **Antar Dasha:** {dasha['current_ad']['lord']}
"""

    if sade["active"]:
        md += f"""
## Sade Sati
- **Status:** {sade['phase']}
- **Guidance:** {sade['guidance']}
"""

    md += f"""
## Full Dasha Timeline
| Lord | Level | Start | End | Years |
|------|-------|-------|-----|-------|
"""
    for d in dasha["dashas"]:
        md += f"| {d['lord']} | MD | {d['start']} | {d['end']} | {d['years']} |\n"

    md += f"""
## Yogas (Auto-Detected)
"""

    # Detect basic Yogas
    grahas = chart["grahas"]
    yogas = []

    # Budha-Aditya Yoga: Sun + Mercury in same sign
    if grahas.get("Surya", {}).get("rashi") == grahas.get("Budha", {}).get("rashi"):
        yogas.append(("Budha-Aditya Yoga", "Intelligence, communication, eloquence"))

    # Gaja-Kesari Yoga: Jupiter + Moon in Kendra from each other
    chandra = grahas.get("Chandra", {})
    guru = grahas.get("Guru", {})
    if chandra and guru:
        moon_sign = int(chandra.get("lon", 0) / 30)
        jup_sign = int(guru.get("lon", 0) / 30)
        dist = (jup_sign - moon_sign) % 12
        if dist == 0 or dist == 4 or dist == 8:
            yogas.append(("Gaja-Kesari Yoga", "Sagesse, autorite, respect"))

    # Chandra-Mangala Yoga: Moon + Mars
    if grahas.get("Chandra", {}).get("rashi") == grahas.get("Mangala", {}).get("rashi"):
        yogas.append(("Chandra-Mangala Yoga", "Passion, courage, leadership"))

    if yogas:
        for name, desc in yogas:
            md += f"- **{name}:** {desc}\n"
    else:
        md += "- No major Yogas auto-detected in D1\n"

    return md


def main():
    parser = argparse.ArgumentParser(description="ASTRA Birth Profile Generator")
    parser.add_argument("--base-dir", default=".", help="FounderHQ root directory")
    parser.add_argument("--date", required=True, help="Birth date YYYY-MM-DD")
    parser.add_argument("--time", default="12:00", help="Birth time HH:MM")
    parser.add_argument("--place", default="Lome", help="Birth place")
    args = parser.parse_args()

    date_parts = args.date.split("-")
    time_parts = args.time.split(":")
    year, month, day = int(date_parts[0]), int(date_parts[1]), int(date_parts[2])
    hour, minute = int(time_parts[0]), int(time_parts[1])

    engine = AstraEngine()
    try:
        md = generate_birth_md(engine, year, month, day, hour, minute, args.place)
    except Exception as e:
        print(f"Error generating birth profile: {e}")
        sys.exit(1)

    base = Path(args.base_dir)
    birth_path = base / "State" / "ASTRA_BIRTH.md"
    birth_path.parent.mkdir(parents=True, exist_ok=True)
    birth_path.write_text(md, encoding="utf-8")
    print(f"Birth profile written: {birth_path}")
    print("Done. Run astra_daily.py to generate today's guidance.")


if __name__ == "__main__":
    main()
