#!/usr/bin/env python3
"""
venture_intake.py — VAOS Venture Intake

Makes the VAOS cascade mechanical and repeatable.
Two modes: interactive guided intake or quick intake from existing text.

Usage:
    python venture_intake.py --help
    python venture_intake.py --interactive "My Project"
    python venture_intake.py --from-text "AI platform for farmers" --project "MYPROJECT" --mode quick
"""

import argparse
import os
import re
import sys
from datetime import datetime, timezone

BASE_DIR = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", "..", ".."))
FOUNDEROS_DIR = os.path.join(BASE_DIR, "FounderOS")
PROJECTS_DIR = os.path.join(FOUNDEROS_DIR, "projects")
STATE_DIR = os.path.join(FOUNDEROS_DIR, "State")
CONCEPTS_DIR = os.path.join(FOUNDEROS_DIR, "concepts")

MODULE_ORDER = [
    "vision",
    "mission",
    "theory_of_change",
    "assets",
    "strategy",
    "roadmap",
    "capital",
    "business_plan",
]

QUICK_MODULES = ["vision", "mission", "business_plan"]

ANSWER_KEYS = {
    "vision": [
        "world_after",
        "problem",
        "advantage",
        "vision_phrase",
        "vision_summary",
    ],
    "mission": [
        "action",
        "audience",
        "approach",
        "mission_statement",
    ],
    "theory_of_change": [
        "action_if",
        "immediate_outcome",
        "immediate_reason",
        "intermediate_outcome",
        "intermediate_reason",
        "long_term_impact",
        "long_term_reason",
        "riskiest_assumption",
    ],
    "assets": [
        "relationships_have",
        "relationships_need",
        "knowledge_have",
        "knowledge_need",
        "resources_have",
        "resources_need",
        "skills_have",
        "skills_need",
        "distribution_have",
        "distribution_need",
    ],
    "strategy": [
        "objective",
        "budget",
        "main_constraint",
        "phase_1_name",
        "phase_1_action",
        "phase_1_cost",
        "phase_1_success",
        "phase_1_fallback",
        "phase_2_name",
        "phase_2_action",
        "phase_2_cost",
        "phase_2_success",
        "phase_2_fallback",
        "phase_3_name",
        "phase_3_action",
        "phase_3_cost",
        "phase_3_success",
        "phase_3_fallback",
    ],
    "roadmap": [
        "phase_1_name",
        "phase_1_start",
        "phase_1_end",
        "phase_1_goal",
        "phase_1_gate",
        "milestone_1",
        "milestone_1_date",
        "milestone_2",
        "milestone_2_date",
        "milestone_3",
        "milestone_3_date",
        "phase_2_name",
        "phase_2_gate",
    ],
    "capital": [
        "validation_budget",
        "validation_source",
        "validation_risk",
        "launch_budget",
        "launch_source",
        "growth_budget",
        "growth_source",
    ],
    "business_plan": [
        "executive_summary",
        "revenue_model",
        "unit_cost",
        "unit_price",
        "unit_margin",
        "breakeven",
        "risk_1",
        "risk_1_prob",
        "risk_1_mitigation",
        "risk_2",
        "risk_2_prob",
        "risk_2_mitigation",
        "risk_3",
        "risk_3_prob",
        "risk_3_mitigation",
    ],
}

INTENT_MATRIX = {
    "vision": {
        "name": "Vision",
        "file": "01_VISION.md",
        "prompt": "Define the transformation of reality this venture creates.",
        "questions": [
            "Quel est le monde APRES la reussite de ce projet ? Decris-le concretement.",
            "Quel est le probleme fondamental que tu resous ?",
            "Pourquoi toi ? Quel est ton avantage asymetrique ?",
            "En une phrase : quelle est la vision ?",
        ],
        "template": """# {PROJECT_NAME} VISION
## Version 1.0

### {vision_phrase}

---

## Vision Resumee
**{vision_summary}**

---

# 1. Le Monde Apres {PROJECT_NAME}
{world_after}

# 2. Le Probleme
{problem}

# 3. L'Avantage Asymetrique
{advantage}

---
*Generated by venture_intake.py | VAOS VISION_ENGINE*
""",
    },
    "mission": {
        "name": "Mission",
        "file": "02_MISSION.md",
        "prompt": "Define the approach -- what do we do, for whom, and how?",
        "questions": [
            "Qu'est-ce que tu fais concretement ? (action)",
            "Pour qui ? (audience cible)",
            "Comment ? (approche/methode)",
            "Formule ta mission : [Venture] existe pour [action] [audience] a travers [approche].",
        ],
        "template": """# {PROJECT_NAME} MISSION

**Mission:** {mission_statement}

## Details
- **Action:** {action}
- **Audience:** {audience}
- **Approche:** {approach}

## Test
- [ ] Specifique ? Peut-on dire 'non' a des choses en dehors ?
- [ ] Decrit ce qu'on fait, pas ce qu'on croit ?
- [ ] Une nouvelle personne peut lire et savoir si elle doit s'interesser ?

---
*Generated by venture_intake.py | VAOS MISSION_ENGINE*
""",
    },
    "theory_of_change": {
        "name": "Theorie du Changement",
        "file": "03_THEORY_OF_CHANGE.md",
        "prompt": "Make explicit the causal chain from actions to outcomes to impact.",
        "questions": [
            "Si tu fais [action X], alors quel est le resultat immediat ?",
            "Si ce resultat immediat arrive, alors quel est le resultat intermediaire ?",
            "Si ce resultat intermediaire arrive, alors quel est l'impact long-terme ?",
            "Quelle est l'hypothese la plus risquee dans cette chaine ?",
        ],
        "template": """# {PROJECT_NAME} -- Theorie du Changement

## Chaine Causale
1. **Si** {action_if}
   **Alors** {immediate_outcome}
   **Parce que** {immediate_reason}

2. **Si** {immediate_outcome}
   **Alors** {intermediate_outcome}
   **Parce que** {intermediate_reason}

3. **Si** {intermediate_outcome}
   **Alors** {long_term_impact}
   **Parce que** {long_term_reason}

## Hypothese la Plus Risquee
{riskiest_assumption}

---
*Generated by venture_intake.py | VAOS THEORY_OF_CHANGE*
""",
    },
    "assets": {
        "name": "Cartographie des Actifs",
        "file": "04_ASSET_MAPPING.md",
        "prompt": "Inventory what we have and identify critical gaps.",
        "questions": [
            "Relations : qui connais-tu qui peut aider ? (partenaires, fournisseurs, mentors, clients)",
            "Connaissances : que sais-tu deja sur ce domaine ?",
            "Ressources : combien de cash, stock, equipement as-tu ?",
            "Competences : que sais-tu faire ? Que dois-tu apprendre ?",
            "Distribution : quelles plateformes/audiences as-tu deja ?",
        ],
        "template": """# {PROJECT_NAME} -- Actifs et Gaps

| Categorie | Actifs | Gaps |
|-----------|--------|------|
| Relations | {relationships_have} | {relationships_need} |
| Connaissances | {knowledge_have} | {knowledge_need} |
| Ressources | {resources_have} | {resources_need} |
| Competences | {skills_have} | {skills_need} |
| Distribution | {distribution_have} | {distribution_need} |

---
*Generated by venture_intake.py | VAOS ASSET_MAPPING*
""",
    },
    "strategy": {
        "name": "Plan Strategique",
        "file": "05_STRATEGIC_PLAN.md",
        "prompt": "Define the plan of attack: what, in what order, with what resources.",
        "questions": [
            "Quel est l'objectif principal pour les 90 prochains jours ?",
            "Quelles sont les 3 etapes cles pour y arriver ?",
            "De quoi as-tu besoin pour chaque etape ? (cash, temps, competences)",
            "Que faire si une etape echoue ? (fallback)",
        ],
        "template": """# {PROJECT_NAME} -- Plan Strategique

**Objectif 90 jours:** {objective}
**Budget:** {budget}
**Contrainte principale:** {main_constraint}

## Phases
### Phase 1: {phase_1_name}
- Action: {phase_1_action}
- Cout: {phase_1_cost}
- Succes: {phase_1_success}
- Fallback: {phase_1_fallback}

### Phase 2: {phase_2_name}
- Action: {phase_2_action}
- Cout: {phase_2_cost}
- Succes: {phase_2_success}
- Fallback: {phase_2_fallback}

### Phase 3: {phase_3_name}
- Action: {phase_3_action}
- Cout: {phase_3_cost}
- Succes: {phase_3_success}
- Fallback: {phase_3_fallback}

---
*Generated by venture_intake.py | VAOS STRATEGIC_PLANNING*
""",
    },
    "roadmap": {
        "name": "Roadmap",
        "file": "06_ROADMAP.md",
        "prompt": "Translate strategy into time-bound phases with gates.",
        "questions": [
            "Quand commences-tu la Phase 1 ? Quelle est la date de fin ?",
            "Quel est le critere (gate) pour passer a la Phase 2 ?",
            "Quels sont les 3 jalons cles et leurs dates ?",
        ],
        "template": """# {PROJECT_NAME} -- Roadmap

## Phase 1: {phase_1_name} -- {phase_1_start} -> {phase_1_end}
**Goal:** {phase_1_goal}
**Gate:** {phase_1_gate}

### Jalons
1. {milestone_1_date} -- {milestone_1}
2. {milestone_2_date} -- {milestone_2}
3. {milestone_3_date} -- {milestone_3}

## Phase 2: {phase_2_name}
**Gate d'entree:** {phase_2_gate}

---
*Generated by venture_intake.py | VAOS ROADMAP_ENGINE*
""",
    },
    "capital": {
        "name": "Strategie de Capital",
        "file": "07_CAPITAL_STRATEGY.md",
        "prompt": "Determine how the venture will be funded at each stage.",
        "questions": [
            "Quel est le budget minimum pour valider ce projet ?",
            "D'ou vient ce budget ? (personnel, revenue, microfinance, subvention, investisseur)",
            "Quel est le plan si ce budget ne suffit pas ?",
            "Quel est le cout en controle/freedom de chaque source ?",
        ],
        "template": """# {PROJECT_NAME} -- Strategie de Capital

## Phase de Validation
- **Budget:** {validation_budget}
- **Source:** {validation_source}
- **Risque:** {validation_risk}

## Phase de Lancement
- **Budget:** {launch_budget}
- **Source:** {launch_source}

## Phase de Croissance
- **Budget:** {growth_budget}
- **Source:** {growth_source}

---
*Generated by venture_intake.py | VAOS CAPITAL_STRATEGY*
""",
    },
    "business_plan": {
        "name": "Business Plan",
        "file": "08_BUSINESS_PLAN.md",
        "prompt": "Produce an executable and fundable business plan from the VAOS cascade.",
        "questions": [
            "Quel est le modele de revenu ? (vente, abonnement, commission, ...)",
            "Quelle est l'economie unitaire ? (cout de revient, prix de vente, marge)",
            "Quels sont les 3 principaux risques et comment les mitiger ?",
        ],
        "template": """# {PROJECT_NAME} -- Business Plan

## Executive Summary
{executive_summary}

## Modele de Revenu
{revenue_model}

## Economie Unitaire
- **Cout de revient:** {unit_cost}
- **Prix de vente:** {unit_price}
- **Marge:** {unit_margin}
- **Seuil de rentabilite:** {breakeven}

## Risques et Mitigations
| Risque | Probabilite | Mitigation |
|--------|-------------|------------|
| {risk_1} | {risk_1_prob} | {risk_1_mitigation} |
| {risk_2} | {risk_2_prob} | {risk_2_mitigation} |
| {risk_3} | {risk_3_prob} | {risk_3_mitigation} |

---
*Generated by venture_intake.py | VAOS BUSINESS_PLAN_ENGINE*
""",
    },
}


def sanitize_project_name(name: str) -> str:
    name = name.strip().upper()
    name = re.sub(r"[^A-Z0-9_]", "_", name)
    name = re.sub(r"_+", "_", name)
    name = name.strip("_")
    return name or "UNTITLED"


def now_lome() -> str:
    return datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M") + " Lome UTC+0"


def today_str() -> str:
    return datetime.now(timezone.utc).strftime("%Y-%m-%d")


def generate_file(template: str, answers: dict) -> str:
    result = template
    for key, value in answers.items():
        placeholder = "{" + key + "}"
        if placeholder in result:
            result = result.replace(placeholder, str(value))
    return result


def collect_answers_interactive(module_id: str, project_name: str) -> dict:
    module = INTENT_MATRIX[module_id]
    keys = ANSWER_KEYS[module_id]
    questions = module["questions"]

    print(f"\n{'='*60}")
    print(f"  {module['name']} — {module['prompt']}")
    print(f"{'='*60}")

    answers = {"PROJECT_NAME": project_name}
    for i, key in enumerate(keys):
        if i < len(questions):
            print(f"\n  > {questions[i]}")
        else:
            print(f"\n  > (supplementaire)")
        raw = input("  >> ").strip()
        answers[key] = raw
    return answers


def collect_answers_from_text(module_id: str, project_name: str, idea_text: str) -> dict:
    keys = ANSWER_KEYS[module_id]
    answers = {"PROJECT_NAME": project_name}
    if keys:
        answers[keys[0]] = idea_text
    for key in keys[1:]:
        answers[key] = "(a definir)"
    return answers


def run_intake(project_name: str, idea_text: str = "", interactive: bool = True, modules: list = None) -> dict:
    sanitized = sanitize_project_name(project_name)
    proj_dir = os.path.join(PROJECTS_DIR, sanitized)
    knowledge_dir = os.path.join(proj_dir, "knowledge")

    os.makedirs(knowledge_dir, exist_ok=True)

    seed_path = os.path.join(knowledge_dir, "IDEA_SEED.md")
    if not os.path.exists(seed_path):
        with open(seed_path, "w", encoding="utf-8") as f:
            f.write(f"# {sanitized} — IDEA SEED\n\n")
            f.write(f"**Date:** {now_lome()}\n\n")
            f.write(f"{idea_text}\n")
            if not idea_text:
                f.write("(a definir)\n")
            f.write(f"\n---\n*Generated by venture_intake.py*\n")
        print(f"  [CREATED] {seed_path}")
    else:
        print(f"  [SKIP] {seed_path} (existe deja)")

    if modules is None:
        modules = MODULE_ORDER

    generated_files = []
    skipped_files = []
    for mod_id in modules:
        module = INTENT_MATRIX[mod_id]
        file_path = os.path.join(proj_dir, module["file"])

        if os.path.exists(file_path):
            skipped_files.append(module["file"])
            print(f"  [SKIP] {module['file']} (existe deja)")
            continue

        if interactive:
            answers = collect_answers_interactive(mod_id, sanitized)
        else:
            answers = collect_answers_from_text(mod_id, sanitized, idea_text)

        content = generate_file(module["template"], answers)

        with open(file_path, "w", encoding="utf-8") as f:
            f.write(content)
        generated_files.append(module["file"])
        print(f"  [CREATED] {file_path}")

    summary = {
        "project_name": sanitized,
        "project_dir": proj_dir,
        "generated_files": generated_files,
        "skipped_files": skipped_files,
    }

    update_master_index(sanitized)
    update_current_state(sanitized)
    update_timeline(sanitized)

    return summary


def update_master_index(project_name: str, phase: str = "IDEA"):
    index_path = os.path.join(PROJECTS_DIR, "PROJECTS_MASTER_INDEX.md")
    if not os.path.exists(index_path):
        print(f"  [WARN] PROJECTS_MASTER_INDEX.md not found at {index_path}")
        return

    with open(index_path, "r", encoding="utf-8") as f:
        content = f.read()

    if f"| {project_name} |" in content:
        print(f"  [SKIP] Master index: {project_name} already listed")
        return

    folder = f"projects/{project_name}/"
    new_row = f"| {project_name} | {phase} | {folder} | -- | -- | Medium | 🟡 |"
    today = today_str()
    now = now_lome()

    content = content.replace(
        "Last Updated:", f"Last Updated: {today}"
    )

    insert_pos = content.find("## Idea / Backlog")
    if insert_pos == -1:
        insert_pos = content.find("## Active")
        if insert_pos == -1:
            content += f"\n{new_row}\n"
        else:
            table_end = content.find("\n\n", insert_pos)
            if table_end == -1:
                table_end = len(content)
            content = content[:table_end] + f"\n{new_row}\n" + content[table_end:]
    else:
        content = content[:insert_pos] + f"{new_row}\n\n" + content[insert_pos:]

    with open(index_path, "w", encoding="utf-8") as f:
        f.write(content)
    print(f"  [UPDATED] PROJECTS_MASTER_INDEX.md — added {project_name}")


def update_current_state(project_name: str):
    state_path = os.path.join(STATE_DIR, "CURRENT_STATE.md")
    if not os.path.exists(state_path):
        print(f"  [WARN] CURRENT_STATE.md not found at {state_path}")
        return

    with open(state_path, "r", encoding="utf-8") as f:
        content = f.read()

    now = now_lome()
    if "## Current State" not in content:
        print(f"  [SKIP] CURRENT_STATE.md — no ## Current State section")
        return

    content = re.sub(
        r"(\*\*Last Updated:\*\*).*",
        f"**Last Updated:** {now}",
        content,
    )

    lines = content.split("\n")
    new_lines = []
    prio_inserted = False
    top_prio_line = None
    top_prio_idx = None

    for i, line in enumerate(lines):
        if line.strip().startswith("**Top Priority:**"):
            top_prio_line = line
            top_prio_idx = i
        new_lines.append(line)

    if top_prio_idx is not None and f"{project_name}" not in top_prio_line:
        new_lines[top_prio_idx] = f"{top_prio_line} | Venture intake: {project_name}"

    with open(state_path, "w", encoding="utf-8") as f:
        f.write("\n".join(new_lines))
    print(f"  [UPDATED] CURRENT_STATE.md")


def update_timeline(project_name: str):
    timeline_path = os.path.join(CONCEPTS_DIR, "TIMELINE.md")
    if not os.path.exists(timeline_path):
        print(f"  [WARN] TIMELINE.md not found at {timeline_path}")
        return

    with open(timeline_path, "r", encoding="utf-8") as f:
        content = f.read()

    today = today_str()
    entry = f"\n**{today}**\n- Venture intake started for {project_name}\n"

    june_header = "### June"
    if june_header in content:
        content = content.replace(june_header, june_header + entry)
    else:
        content += f"\n### {today[:7]}\n{entry}"

    with open(timeline_path, "w", encoding="utf-8") as f:
        f.write(content)
    print(f"  [UPDATED] TIMELINE.md — added {project_name} intake event")


def main():
    parser = argparse.ArgumentParser(description="VAOS Venture Intake — mechanical VAOS cascade")
    parser.add_argument(
        "--interactive",
        nargs="?",
        const="",
        default=None,
        help="Start interactive intake. Optionally provide project name.",
    )
    parser.add_argument("--from-text", type=str, help="Quick intake from idea text")
    parser.add_argument("--project", type=str, help="Project name (required for --from-text)")
    parser.add_argument(
        "--mode",
        choices=["quick", "full"],
        default="quick",
        help="quick=vision+mission+BP only, full=all modules (default: quick)",
    )

    args = parser.parse_args()

    if args.interactive is not None:
        if args.interactive:
            project_name = args.interactive
        else:
            project_name = input("Nom du projet: ").strip()
        idea = input("Decris ton idee en 2-3 phrases: ").strip()

        modules = MODULE_ORDER if args.mode == "full" else QUICK_MODULES
        result = run_intake(project_name, idea, interactive=True, modules=modules)
        print(f"\n{'='*60}")
        print(f"  Projet {result['project_name']} cree.")
        print(f"  {len(result['generated_files'])} fichiers generes.")
        if result['skipped_files']:
            print(f"  {len(result['skipped_files'])} fichiers ignores (existaient deja).")
        print(f"  Dossier: projects/{result['project_name']}/")
        if args.mode == "quick":
            print(f"  Suggestion: relancer en mode full pour tout le cascade VAOS.")
        print(f"{'='*60}")

    elif args.from_text:
        if not args.project:
            print("ERROR: --project is required with --from-text")
            sys.exit(1)

        modules = MODULE_ORDER if args.mode == "full" else QUICK_MODULES
        result = run_intake(args.project, args.from_text, interactive=False, modules=modules)
        print(f"\n{'='*60}")
        print(f"  Projet {args.project} cree (mode {'quick' if args.mode == 'quick' else 'full'}).")
        print(f"  {len(result['generated_files'])} fichiers generes.")
        if result['skipped_files']:
            print(f"  {len(result['skipped_files'])} fichiers ignores (existaient deja).")
        print(f"  Suggestion: lancer interactif pour completer:")
        print(f"    python FounderOS/Runtime/engine/venture_intake.py --interactive {args.project} --mode full")
        print(f"{'='*60}")

    else:
        parser.print_help()


if __name__ == "__main__":
    main()
